---

name: 'equal-weighting'
start: '1963-07-01'
end: '2021-12-31'

# Alternative rebalancing frequencies
rebal_freq: ['1MS','3MS','6MS','1YS','3YS','5YS']     # Rebalancing frequencies as used in pd.Grouper
rebal_factors: [12, 4, 2, 1, 0.333333, 0.2]                # Factors associated with above freq to calculate annualised returns

# Colors used for plotting
col_palette:
  "grey": '#1A4645'
  "teal": '#266867'
  "orange": '#F58800'
  "yellow": '#F8BC24'
  "black": '#051821'
  "red": '#E74C3C'